export default {
  'app.title': 'Apple Music',
  'app.intro': 'I am going to recreate the Apple Music UI in React. Then Flux. Then with Relay.',
  'app.album': 'album',
  'app.albums': 'albums',
  'app.artist': 'artist',
  'app.artists': 'artists',
  'player.by': 'by',
  'player.from': 'from',
  'player.nothing': 'Nothing is playing.',
  'album.song': 'song',
  'album.songs': 'songs',
  hour: 'hour',
  hours: 'hours',
  minute: 'minute',
  minutes: 'minutes',
};
