export default {
  'app.title': 'Apple Music',
  'app.intro': 'I am going to recreate the Apple Music UI in React. Then Flux. Then with Relay.',
  'app.album': 'album',
  'app.albums': 'albums',
  'app.artist': 'artist',
  'app.artists': 'artists',
  'player.by': 'by',
  'player.from': 'from',
  'player.nothing': 'Nothing is playing.',
  'album.song': 'song',
  'album.songs': 'songs',
  'artist.top_songs': 'Top Songs',
  'artist.albums': 'Albums',
  'artist.related_artists': 'Related Artists',
  'search.results': 'Search Results for "{term}"',
  'search.placeholder': 'Search for artists, albums, and tracks',
  'search.no_artists_found': 'No artists found.',
  'search.no_albums_found': 'No albums found.',
  'search.no_tracks_found': 'No tracks found.',
  'search.tracks': 'Tracks',
  'search.artists': 'Artists',
  'search.albums': 'Albums',
  hour: 'hour',
  hours: 'hours',
  minute: 'minute',
  minutes: 'minutes',
  next: 'Next',
  previous: 'Previous',
};
