export default {
  'app.title': 'Apple Música',
  'app.intro': 'Voy a recrear la Apple Music UI en React. Luego Flux. Luego con Relay.',
  'app.album': 'álbum',
  'app.albums': 'álbumes',
  'app.artist': 'artista',
  'app.artists': 'artistas',
  'player.by': 'por',
  'player.from': 'de',
  'player.nothing': 'Nada está jugando.',
  'album.song': 'canción',
  'album.songs': 'canciones',
  'artist.top_songs': 'Mejores canciones',
  'artist.albums': 'Álbumes',
  'artist.related_artists': 'Artistas relacionados',
  'search.results': 'Resultados de la búsqueda para "{term}"',
  'search.placeholder': 'Búsqueda de artistas, álbumes y pistas',
  'search.no_artists_found': 'No se han encontrado artistas.',
  'search.no_albums_found': 'No se encontraron álbumes.',
  'search.no_tracks_found': 'No se encontraron pistas.',
  'search.tracks': 'Pistas',
  'search.artists': 'Artistas',
  'search.albums': 'Álbumes',
  hour: 'hora',
  hours: 'horas',
  minute: 'minuto',
  minutes: 'minutos',
  next: 'Siguiente',
  previous: 'Anterior',
};
